<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>k8s-core</artifactId>

    <parent>
        <groupId>com.coding</groupId>
        <artifactId>k8s-cloud-platform</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>


    <dependencies>
        <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>kubernetes-client</artifactId>
            <version>${fabric8.kubernetes-client.version}</version>
        </dependency>

        <dependency>
            <groupId>com.coding</groupId>
            <artifactId>platform-common</artifactId>
            <version>${project.parent.version}</version>
        </dependency>

        <dependency>
            <groupId>com.coding</groupId>
            <artifactId>platform-data</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
        
    </dependencies>



</project>
