server:
  port: 9527

# MyBatis 配置
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.coding.data.models
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
knife4j:
  enable: true
  setting:
    language: zh_cn

spring:
  security:
    oauth2:
      authorizationserver:
        issuer: ${OAUTH2_SERVER:http://127.0.0.1:9527}
    ignore-urls:
      - "/actuator/**"
      - "/doc.html"
      - "/assets/**"
      - "/login.html"
      - "/user/login"
      - "/user/logout"
      - "/register.html"
      - "/forgot-password.html"
      - "/404"
      - "/500"
      - "/v3/api-docs/**"
      - "/v2/api-docs"
      - "/swagger-ui/**"
      - "/swagger-ui.html"
      - "/swagger-resources/**"
      - "/webjars/**"
      - "/test/**"
      - "/favicon.ico"
      - "/favicon-dark.svg"
      - "/favicon-light.svg"
      - "/.well-known/**"
      - "/manifest.json"

  servlet:
    multipart:
      max-file-size: 5120MB
      max-request-size: 5120MB
      enabled: true
  application:
    name: platform-auth
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://192.168.31.80:1234/k8s_cloud_platform?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:coding}
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 0
      connection-test-query: SELECT 1
jwt:
  enabled: true
  issuer: ${OAUTH2_SERVER:http://127.0.0.1:9527}
  data-key: data
logging:
  level:
    root: info